### ISSUE TITLE
Catch errors when decoding ASCII

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ElectricRCAircraftGuy/eRCaGuy_PyTerm#3]
Do a try/catch around this line, and gracefully handle errors when the chars are binary instead of ASCII: https://github.com/ElectricRCAircraftGuy/eRCaGuy_PyTerm/blob/1274e811881b6de3acc5d30c4da6854d89f85192/serial_terminal.py#L151

Sometimes garbled data comes over serial, crashing the program otherwise when an invalid (ie: binary instead of ASCII) byte arrives.

**Comment by ElectricRCAircraftGuy** [comment]
Example error: 

```
auto-flusTraceback (most recent call last):
  File "C:\Users\gabriel\GS\dev\eRCaGuy_PyTerm\serial_terminal.py", line 264, in <module>

    main()
  File "C:\Users\gabriel\GS\dev\eRCaGuy_PyTerm\serial_terminal.py", line 151, in main
    data_str = data_bytes.decode('ascii')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf9 in position 3: ordinal not in range(128)
```
